Friend Module Choices
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const CraftText = "Craft..."
    Friend Const DeepWaterText = "Deep Water"
    Friend Const GameMenuText = "Game Menu"
    Friend Const HeadsText = "Heads"
    Friend Const InventoryText = "Inventory"
    Friend Const LoadGameText = "Load Game..."
    Friend Const MoveText = "Move..."
    Friend Const NeverMindText = "Never Mind"
    Friend Const NewGameText = "New Game"
    Friend Const NoText = "No"
    Friend Const QuitText = "Quit"
    Friend Const ResumeGameText = "Resume Game"
    Friend Const SaveGameText = "Save Game..."
    Friend Const ShallowWaterText = "Shallow Water"
    Friend Const StatusText = "Status"
    Friend Const TailsText = "Tails"
    Friend Const YesText = "Yes"
End Module
